### USERS

GET http://localhost:4000/navbars/published

###

PATCH http://localhost:4000/users/6033891cb9538243b0b23061
Content-Type: application/json

{
  "name": "name",
  "password": "password",
  "email": "email2"
}

###

POST http://localhost:4000/navbars
Content-Type: application/json

{
  "published": true,
  "items": [
    {
      "x":  0,
      "name": "",
      "pages": []
    },
    {
      "x":  1,
      "name": "",
      "pages": []
    },
    {
      "x":  2,
      "name": "",
      "pages": []
    },
    {
      "x":  3,
      "name": "",
      "pages": []
    },
    {
      "x":  4,
      "name": "",
      "pages": []
    },
    {
      "x":  5,
      "name": "",
      "pages": []
    },
    {
      "x":  6,
      "name": "",
      "pages": []
    },
    {
      "x":  7,
      "name": "",
      "pages": []
    }
  ],
  "created_by": "603b5ed1b0be270fb4eaf5bd"
}

###

POST http://localhost:4000/modules
Content-Type: application/json

{
  "page_id": "604dcce0a7aebd252c2c5b56",
  "type": "custom-image",
  "position": {
    "x": 2,
    "y": 0,
    "w": 2,
    "h": 1
  },
  "body": {
  "src": "https://picsum.photos/1980/1720",
    "alt": "custom-image",
    "title": "Title placeholder",
    "subtitle": "Subtitle placeholder",
    "objectFit": "none"
  }
}

###

#POST http://localhost:4000/auth
#Content-Type: application/json
#
#{
#    "email": 'ja',
#    "password": 'ja'
#}